### ISSUE TITLE
Flight Cheapest Date Search

### ISSUE THREAD

**Issue by baqwas** [amadeus4dev/amadeus-python#82] opened 2020-03-08 05:10 UTC
## Description

Not an issue, sorry, but unable to **GET** any usable data! Cannot get meaningful data using DFW as the origin airport. For example, cheapest flight date search does not return any data. Non-stop flights are not listed when seeking flights between **DFW** and **DOH** or **DXB** during **December 2020**.

## Steps to Reproduce

1. Ran `amadeus.shopping.flight_offers.get(origin='DFW', destination='DOH', departureDate='2020-12-12')`
Response had a whole lot of solid data but JSONata exerciser reported:
`ERROR IN INPUT DATA: JSON.parse: unexpected non-whitespace character after JSON data at line 2852 column 1 of the JSON data` Had to suspend JSON parsing.
2. Ran `amadeus.shopping.flight_dates.get(origin='DFW', destination='LHR')`
Response was Error 500 as noted below.
3. Struggling to get usable (_i.e._ practical data with origin as DFW) for testing purposes. Would like to get my code/parsing working in test mode before embarking on production pricing schedule. I understand the challenges in servicing international customers but there should be some elementary filters and sorting to suppress valid but unworkable data (_e.g._ routing such as DFW->HKG->DOH or DFW->ORD->FRA->AMM->DOH; may be useful in some customers but for introductory testing this subset is highly debatable unless one has extended development time).

4. All workarounds remain unproductive (cannot call it unsuccessful!):
* Javascript
* Python (with and without Jupyter)
* Test at `https://test.api.amadeus.com/v1/shopping/` confirmed the challenges previous two steps.

__Expected Behavior:__ Response object containing valid data

__Actual Behavior:__ Error status 500
```
{
  "errors": [
    {
      "status": 500,
      "code": 141,
      "title": "SYSTEM ERROR HAS OCCURRED",
      "detail": "DATA DOMAIN NOT FOUND FOR REQUEST"
    }
  ]
}
```

__Stable Behavior?__ 100% for any city pair originating from DFW

## Versions

Python 3.7
Ubuntu 19.10

## Checklist

Please make sure you checked the following:

* Running **Python 3.7**
* Installed using **pip** v18.1 in _/usr/lib/python3/dist-packages/pip_ (python 3.7)

**Comment by anthonyroux** [comment] 2020-03-08 20:15
Hi,

Regarding `Flight Cheapest Date Search`: in the test environment, we offer only a subset of the data we have in production. You can find the list of supported origin-destination [here](https://github.com/amadeus4dev/data-collection).

In production, we offer more origin-destination but the Flight Cheapest Date Search is an inspiration API built on top of a cache:  you can search only a maximum of 6 months in advance, for a maximum trip duration of 15 days.

As you can see in the data-collection we offer some DFW -> destinations but not DFW -> LHR. I played around with the API in test and I can confirm it works fine if you use data available in test. We fully understand that you want to try the API in the test environment before moving to production, this is why we offer a free of charge access but limited. Note that even if you get access to production, we offer the same free quota in production that we offer in the test environment (every month!). In general, keep in mind that this API is an inspiration API built on top of a cache. We are working to increase the coverage of this cache (both in test and in production) but in any case, you will have to call the `Flight Offers Search API` to get accurate data and full coverage.

I tried the Python SDK and it works fine as well, please find below an example ready to use (just replace your `API KEY` & `API SECRET`:

```py
from amadeus import Client, ResponseError

amadeus = Client(client_id='API_KEY',  client_secret='API_SECRET')

try:
    response = amadeus.shopping.flight_dates.get(origin='DFW', destination='EDI')
    print(response.data)
except ResponseError as error:
    raise error
```

There is an easy way to get the different destinations available from an origin:
- Call first the Flight Inspiration API (here with `DFW` as origin)
- Get the list of destinations available for DFW
- Use this list in the cheapest date search

Regarding your point `1` I tried that piece of code with the latest version of our SDK and it works perfectly fine. Please find below the full working example:

```py
from amadeus import Client, ResponseError

amadeus = Client(client_id='API_KEY',  client_secret='API_SECRET')
try:
    response = amadeus.shopping.flight_offers.get(origin='DFW', destination='DOH', departureDate='2020-12-12')
    print(response.data)
except ResponseError as error:
    raise error
```
Please make sure you have an updated version fo the SDK, if it is the case it might be related to your working environment/code.

My last comment: in your example, you are using the `Flight Low-fare Search API`, this API will be decommissioned in the coming month, I strongly recommend you to use the `Flight Offers Search API` instead (it offers more content/capabilities and a better API design). The API is available in the Python SDK.

Hope it clarifies.

Regards,
Anthony

**Closed by anthonyroux** 2020-03-08 20:15 UTC

**Comment by baqwas** [comment] 2020-03-08 23:26
Thx @anthonyroux for the prompt update. Understand the deprecation of the call I used to illustrate my JavaScript challenges. The `Flight Offers Search` works fine for me in my Jupyter notebook where I have tested all the **Air** related calls.

Based on your recommendation, I look forward to moving to the _Production_ environment shortly since the pricing is pro-rated and I will only make a few daily calls to a subset of the **Air** services. The Node-RED approach was intended to send notifications to my Home Automation dashboard. I guess I'll do a half-and-half solution initially in the _Production_ environment.

Understand your comments about the test data and I have no issue on that aspect.

Kind regards.

**Comment by anthonyroux** [comment] 2020-03-09 10:05
Great! Make sure you monitor carefully the number of API calls you do per month (you can use the dashboard in your workspace).

**Comment by jasisz** [comment] 2020-07-08 10:57
@anthonyroux I got the same on the production environment, e.g.: I can't get any results for WAW->LON, while LON->WAW works fine.
Is there any list of workin connections for production as this one seems to be for testing env https://github.com/amadeus4dev/data-collection/blob/master/data/flightsearch.md ?

**Comment by anthonyroux** [comment] 2020-07-09 08:40
Hey @jasisz, this is because we have selected LON -> WAW as an "important" segment whereas WAW -> LON was not.


The test environment is based on a subset of the production data. In case you want to see what data is available in test please refer to the test [data collection on GitHub][

Flight Cheapest Date Search and Flight Inspiration Search are inspirational APIs, we build a cache on pre-selected sets of origin-destination this is why even in production you will not find every route. If you want to get access to all routes you need to use the live search Flight Offers Search. We are actually working on a new version of the cache used by Flight Cheapest Date that will offer better data in test and in production (and a smarter coverage). As of today, we do not provide the list of routes available in production, this is something we are discussing for the new version of the cache.
